language: python
python:
  - 3.8.10
install:
  - pip install -r requirements.txt
  - pip install coverage

scripts:
  "coverage run -m unittest discover -s . -p '**/genre_tests.py'"
notifications:
  email:
    reciplients:
      - vasylivna.nv@gmail.com
    on_success: never
    on_failure: always

