language: python
python:
  - 3.8.10
install:
  - pip install -r requirements.txt

scripts:
  - python -m unittest bookstore_app.tests.unit.genre_unit_tests
  - python -m unittest bookstore_app.tests.unit.author_unit_tests
  - python -m unittest bookstore_app.tests.unit.book_unit_tests
  - coverage run -m unittest
notifications:
  email:
    reciplients:
      - vasylivna.nv@gmail.com
    on_success: never
    on_failure: always