language: python
python:
  - 3.8.10
install:
  - pip install -r requirements.txt
  - pip install bookstore_app


scripts:
  - python bookstore_app/tests/genre_test.py
notifications:
  email:
    reciplients:
      - vasylivna.nv@gmail.com
    on_success: never
    on_failure: always

