language: python
python:
  - 3.8.10
install:
  - pip install -r requirements.txt


notifications:
  email:
    reciplients:
      - vasylivna.nv@gmail.com
    on_success: never
    on_failure: always

